// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vujnqatklepfkthqjhcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1am5xYXRrbGVwZmt0aHFqaGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NjY1MDIsImV4cCI6MjA1MTE0MjUwMn0.ZcEaSeWh-txYnAEcOELNGh2_p0IucJQ7sRdE8uykpi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);